version: '3.7'

services:
  svxreflector:
    container_name: svxreflector
    image: svxlink
    command: "/usr/bin/svxreflector"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5300:5300
    environment:
#     - GIT_BRANCH=master # To build another branch than master
      - NUM_CORES=4 # To use more than one CPU core when compiling
#     - GIT_URL=username@your.repo:/path/to/svxlink.git # To use a specific git repositoty instead of the default one
    volumes:
      - $PWD/config/svxreflector.conf:/etc/svxlink/svxreflector.conf:ro
      - $PWD/config/svxlink.d:/etc/svxlink/svxlink.d:ro
    restart: unless-stopped
